"""del role_position_raw

Revision ID: 907c65a1ef76
Revises: cd6b696d6ae6
Create Date: 2026-07-11 11:54:36.466659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '907c65a1ef76'
down_revision: Union[str, Sequence[str], None] = 'cd6b696d6ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'role_position_raw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('role_position_raw', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
