"""initial schema

Revision ID: cd6b696d6ae6
Revises: 
Create Date: 2026-07-07 16:52:07.554910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd6b696d6ae6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('system_text', sa.Text(), nullable=False),
    sa.Column('user_template', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_prompts_name_version')
    )
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.String(), nullable=False),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('about_me_summary_raw', sa.Text(), nullable=True),
    sa.Column('role_position_raw', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role_position', sa.String(), nullable=True),
    sa.Column('about_summary', sa.Text(), nullable=True),
    sa.Column('about_llm', sa.String(), nullable=True),
    sa.Column('about_prompt_id', sa.Integer(), nullable=True),
    sa.Column('feedback_raw', sa.Text(), nullable=True),
    sa.Column('feedback_summary', sa.Text(), nullable=True),
    sa.Column('feedback_sections', sa.JSON(), nullable=True),
    sa.Column('feedback_llm', sa.String(), nullable=True),
    sa.Column('feedback_prompt_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['about_prompt_id'], ['prompts.id'], ),
    sa.ForeignKeyConstraint(['feedback_prompt_id'], ['prompts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resumes_about_llm_prompt', 'resumes', ['about_llm', 'about_prompt_id'], unique=False)
    op.create_index('idx_resumes_feedback_llm_prompt', 'resumes', ['feedback_llm', 'feedback_prompt_id'], unique=False)
    op.create_index(op.f('ix_resumes_about_llm'), 'resumes', ['about_llm'], unique=False)
    op.create_index(op.f('ix_resumes_about_prompt_id'), 'resumes', ['about_prompt_id'], unique=False)
    op.create_index(op.f('ix_resumes_feedback_llm'), 'resumes', ['feedback_llm'], unique=False)
    op.create_index(op.f('ix_resumes_feedback_prompt_id'), 'resumes', ['feedback_prompt_id'], unique=False)
    op.create_index(op.f('ix_resumes_resume_id'), 'resumes', ['resume_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumes_resume_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_feedback_prompt_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_feedback_llm'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_about_prompt_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_about_llm'), table_name='resumes')
    op.drop_index('idx_resumes_feedback_llm_prompt', table_name='resumes')
    op.drop_index('idx_resumes_about_llm_prompt', table_name='resumes')
    op.drop_table('resumes')
    op.drop_table('prompts')
    # ### end Alembic commands ###